apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-bouncer
  labels:
    app: image-bouncer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-bouncer
    spec:
      containers:
      - name: image-bouncer
        image: 314315960/image-bouncer:v1.0
        imagePullPolicy: Always
        env:
          - name: WHITELIST_NAMESPACES
            value: "kube-system,default"
          - name: WHITELIST_REGISTRIES
            value: "314315960"
          - name: WEBHOOK_URL
            value: "${WEBHOOK_URL}"
        ports:
          - containerPort: 443
            name: https
        volumeMounts:
        - name: tls
          mountPath: /etc/admission-controller/tls
        resources: {}
      volumes:
        - name: tls
          secret:
            secretName: image-bouncer