apiVersion: v1
kind: Service
metadata:
  name: image-bouncer
  labels:
    app: image-bouncer
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: "TCP"
      name: https
  selector:
    app: image-bouncer